spring:
  application:
    name: Spring-AI-DMR

  ai:
    openai:
      base-url: http://15.206.179.230
      api-key: dummy-key

      embedding:
        options:
          model: ai/embeddinggemma

    vectorstore:
      mongodb:
        collection-name: vector_store
        path-name: embedding
        index-name: vector_index
        initialize-schema: false

logging:
  level:
    org.springframework.ai.autoconfigure: DEBUG

database:
  name: AI_DMR

ai:
  databaseName: AI_DMR
  modelName: smollm2
  temperature: 0.7
  topP: 0.3