spring:
  application:
    name: Spring-AI-DMR

  ai:
    openai:
      base-url: http://13.232.210.112
      api-key: dummy-key

      embedding:
        options:
          model: ai/embeddinggemma

    vectorstore:
      mongodb:
        collection-name: vector_documents
        path-name: embedding
        index-name: vector_index
        initialize-schema: true

logging:
  level:
    org.springframework.ai:
      autoconfigure: DEBUG
      chat.client.advisor: DEBUG


ai:
  databaseName: AI_DMR
  modelName: "gpt-oss:20B"
  temperature: 0.7
  topP: 0.3
  maxTokens: 200
